[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mysqli",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.ctype",
  "php82Extensions.bcmath",
  "php82Extensions.zip",
  "php82Extensions.curl",
  "php82Extensions.openssl",
  "php82Extensions.fileinfo",
  "php82Packages.composer",
  "nodejs_20"
]

[phases.install]
cmds = [
  "mkdir -p bootstrap/cache storage/framework/cache/data storage/framework/sessions storage/framework/views storage/framework/testing storage/app/public storage/app/private storage/logs",
  "chmod -R 775 bootstrap/cache storage",
  "cp .env.example .env",
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --no-scripts",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "sh ./railway-start.sh"
